### ISSUE TITLE
to nie wirus z batcha

### ISSUE THREAD

**Issue by pankoza-pl** [ProgramistaZpolski/slabyWirusPankozyCzyKogosTam#4]
to nie żaden wirus z batcha xD

**Comment by pankoza-pl** [comment]
.

**Comment by ProgramistaZpolski** [comment]
![Screenshot_2021-03-08 ProgramistaZpolski slabyWirusPankozyCzyKogosTam](https://user-images.githubusercontent.com/37271169/110364961-b81d6e00-8044-11eb-9149-ee2d11e980b6.png)

Niech to zdjęcie odpowie za siebie.

**Comment by Creper132** [comment]
jest xD

**Comment by ProgramistaZpolski** [comment]
![Screenshot_2021-03-11 to nie wirus z batcha · Issue #4 · ProgramistaZpolski slabyWirusPankozyCzyKogosTam](https://user-images.githubusercontent.com/37271169/110767893-02763900-8257-11eb-8b6b-4f02fbb0b1c8.png)
90% kodu - batch

jest to wirus z batcha.

**Comment by Creper132** [comment]
Potwierdzam prosze pana pomimo zze az tak ciebier nie lubie

**Comment by Creper132** [comment]
mozemy sie pogodzic podaj dc?

**Comment by ProgramistaZpolski** [comment]
> mozemy sie pogodzic podaj dc?

piotrbadelek@protonmail.com

preferuję nie korzystać z dsc
